### ISSUE TITLE
psql: server closed the connection unexpectedly

### ISSUE THREAD

**Issue by miloskroulik** [vpicavet/docker-pggis#2]
After successfully downloading the container, I did run it with provided command, however, I could not connect to it with local psql because of error:

````
psql: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
````

I saw no errors in ````docker logs````
I am running:
latest Docker
Linux Mint (equivalent to Ubuntu 14.04)
psql 9.3.4

**Comment by vpicavet** [comment]
Fixed the AUFS bug in 1.6 normally + documented workaround.
