### ISSUE TITLE
Running docker-pggis on a Mac runs into file permissions errors

### ISSUE THREAD

**Issue by vielmetti** [vpicavet/docker-pggis#7]
The issue on the Mac is similar to the documented problem where the database comes up the first time, but the second time just leaves a trail of ......... as it tries to load.

On the Mac under boot2docker (or docker-machine) the issue was identified as https://github.com/boot2docker/boot2docker/issues/581 which has to deal with file system UID mappings to the host file system. Alas the documented workaround of using a shell script to connect and fix things doesn't work.

Punting for now, but thought I'd save someone some time who tried this and got stuck. My workaround is the native `Postgres.app` distribution http://postgresapp.com/ (and some kind of native equivalent on AWS as the server side).

**Comment by vpicavet** [comment]
Ok, I will close the issue since the problem is upstream, but thanks for documenting it.
Hopefully it will be fixed soon in boot2docker.
